
[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[context.production]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[context.deploy-preview]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[functions]
  directory = "functions"
  
[[redirects]]
  from = "/*"
  to = "/docs/portal-onboarding-guide/:splat"
  status = 301
  force = false

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "docs"
  filePath = "_build/html/docs/portal-onboarding-guide"
  prettyURLs = true
  trailingSlash = true
